In [25]:
##Task 1 - no.1
def divide():
    try:
        x=5
        y=0
        res = x/y
        print(res)
    except Exception as e:
        print(e)
divide()

division by zero


In [23]:
##Task 1 - no.2
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
for i in subjects:
    for j in verbs:
        for k in objects:
            print(i,j,k)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [3]:
##Task 2 - no.1
import numpy as np
def func(v):
    n = len(v)
    m = []
    for x in v:
        for y in range(0,n):
            m.append(x**(n-y-1))
    a=np.array((m))
    print(a.reshape(n,n))
z = [1,2,3,4,5]
func(z)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [5]:
##OR
##Task 2 - no.1
import numpy as np
def func(z):
    x = np.array(z)
    n = len(x)
    print(np.vander(x,n))
z = [1,2,3,4]
func(z)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
